In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.2'

In [4]:
array_1=np.array([1,2,3])
array_1

array([1, 2, 3])

In [5]:
type(array_1)

numpy.ndarray

In [6]:
array2=np.array([[1,2],
                 [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [8]:
 array_3d=np.array([[
                     [1,2],
                     [3,4]
 ],
 [                   [5,6],
                     [7,8]
 ]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
array_3d_a=np.array([[
                     [1,2,3],
                     [4,5,6],
                     [7,8,9]
 ],
 [                   [10,11,12],
                     [13,14,15],
                     [16,17,18]
 ]])
array_3d_a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
array_3d_a.shape

(2, 3, 3)

In [13]:
array_4d=np.array([
    [
        [[
                     [1,2],
                     [3,4],
                     [5,6]
 ],
 [                   [7,8],
                     [9,10],
                     [11,12]
 ]],
        [[
                     [13,14],
                     [15,16],
                     [17,18]
 ],
 [                   [19,20],
                     [21,22],
                     [23,24]
 ]],
        [[
                     [25,26],
                     [27,28],
                     [29,30]
 ],
 [                   [31,32],
                     [33,34],
                     [35,36]
 ]]
    ],
    [
        [[
                     [37,38],
                     [39,40],
                     [41,42]
 ],
 [                   [43,44],
                     [45,46],
                     [47,48]
 ]],
        [[
                     [49,50],
                     [51,52],
                     [53,54]
 ],
 [                   [55,56],
                     [57,58],
                     [59,60]
 ]],
        [[
                     [61,62],
                     [63,64],
                     [65,66]
 ],
 [                   [67,68],
                     [69,70],
                     [71,72]
 ]]
    ]
])
array_4d

array([[[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]],


        [[[13, 14],
          [15, 16],
          [17, 18]],

         [[19, 20],
          [21, 22],
          [23, 24]]],


        [[[25, 26],
          [27, 28],
          [29, 30]],

         [[31, 32],
          [33, 34],
          [35, 36]]]],



       [[[[37, 38],
          [39, 40],
          [41, 42]],

         [[43, 44],
          [45, 46],
          [47, 48]]],


        [[[49, 50],
          [51, 52],
          [53, 54]],

         [[55, 56],
          [57, 58],
          [59, 60]]],


        [[[61, 62],
          [63, 64],
          [65, 66]],

         [[67, 68],
          [69, 70],
          [71, 72]]]]])